name: "Deploy MTF Utility"

on:
  push:
    tags:
      - "MTFUtility/v*"

env:
  PROJECT_PATH: MTFUtility.csproj

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.x.x

      - run: dotnet restore ${{ env.PROJECT_PATH }}

      - run: dotnet build ${{ env.PROJECT_PATH }} -c Release --no-restore

      - run: dotnet publish ${{ env.PROJECT_PATH }} -c Release --self-contained -r win-x64 -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true --no-build
  
      # - uses: actions/create-release@v1
      #   id: create_release
      #   env:
      #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with: 
      #       tag_name: ${{ github.ref }}
      #       release_name: ${{ github.ref }}

      # - uses: csexton/release-asset-action@v2
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     pattern: MTFUtility/bin/Release/net6.0-windows/publish/win-x64/*.exe
      #     release-url: ${{ steps.create_release.outputs.upload_url }}